/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class demoJNI */

#ifndef _Included_demoJNI
#define _Included_demoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     demoJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_demoJNI_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
